In [1]:
import sys
import os

sys.path.insert(0, os.path.abspath("../src"))

In [2]:
import pandas as pd
from news_loader import load_boursorama_news, load_pappers_company

/Users/ulrichfossokako/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [3]:
# Charger les news Boursorama
news = load_boursorama_news()

print(news.shape)
news.head()

(157, 3)

         date      source                                               text
0  2026-05-10  boursorama  Espace Membre Espace Client Connexion Sur quel...
1  2026-05-10  boursorama  Connexion Sur quel site souhaitez-vous vous co...
4  2026-05-10  boursorama  Bourse Actualités Actualités Points de marchés...
5  2026-05-10  boursorama  Actualités Actualités Points de marchés Actual...
6  2026-05-10  boursorama  Actions Actions Cotations Par marché Internati...

In [4]:
# sauvegarde des news
os.makedirs("../data/raw", exist_ok=True)
news.to_csv("../data/raw/boursorama_news.csv", index=False)

In [5]:
import requests

PAPPERS_API_TOKEN = "19847cc911c81b03eb9d4d636c33b0e30d76e2cf46db4d37"

url = "https://api.pappers.fr/v2/entreprise"
params = {
    "api_token": PAPPERS_API_TOKEN,
    "siren": "775670417"  # LVMH
}

r = requests.get(url, params=params)

print(r.status_code)
print(r.text[:500])

401
{"statusCode":401,"error":"Vous n'avez plus assez de crédits pour effectuer cette requête","message":"Vous pouvez prendre un abonnement supérieur ou acheter des Pay as you go depuis votre espace membre Pappers."}

In [6]:
PAPPERS_API_TOKEN = "eb133f89f5777dde6b40d461d50a9f255544817502576133"

companies = {
    "AIRBUS": "383474814",
    "ALSTOM": "389058447",
    "AXA": "572093920",
    "BNP_PARIBAS": "662042449",
    "BOUYGUES": "572015246",
    "CAPGEMINI": "330703844",
    "CARREFOUR": "652014051",
    "CREDIT_AGRICOLE": "784608416",
    "DANONE": "552032534",
    "DASSAULT_SYSTEMES": "322306440",
    "ENGIE": "542107651",
    "ESSILORLUXOTTICA": "712049618",
    "HERMES": "572076396",
    "KERING": "552075020",
    "LVMH": "775670417",
    "LEGRAND": "421259615",
    "L'OREAL": "632012100",
    "MICHELIN": "855200507",
    "ORANGE": "380129866",
    "PERNOD_RICARD": "582041943",
    "PUBLICIS": "542080601",
    "RENAULT": "780129987",
    "SAFRAN": "562082909",
    "SAINT_GOBAIN": "542039532",
    "SANOFI": "395030844",
    "SCHNEIDER_ELECTRIC": "542048574",
    "SOCIETE_GENERALE": "552120222",
    "STELLANTIS": "542097924",
    "TELEPERFORMANCE": "301292702",
    "THALES": "552059024",
    "TOTALENERGIES": "542051180",
    "UNIBAIL_RODAMCO": "682024096",
    "VEOLIA": "403210032",
    "VINCI": "552037806",
    "VIVENDI": "343134763",
    "WORLDLINE": "378901946"
}

In [7]:
rows = []

for company, siren in companies.items():
    try:
        row = load_pappers_company(PAPPERS_API_TOKEN, siren)
        row["company"] = company
        rows.append(row)
    except Exception as e:
        print(company, e)

pappers_df = pd.DataFrame(rows)
pappers_df

AIRBUS 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=383474814
ALSTOM 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=389058447
AXA 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=572093920
BNP_PARIBAS 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=662042449
BOUYGUES 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=572015246
CAPGEMINI 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=330703844
CARREFOUR 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=652014051
CREDIT_AGRICOLE 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=784608416
DANONE 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=552032534
DASSAULT_SYSTEMES 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=322306440
ENGIE 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=542107651
ESSILORLUXOTTICA 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=712049618
HERMES 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=572076396
KERING 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=552075020
LVMH 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=775670417
LEGRAND 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=421259615
L'OREAL 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=632012100
MICHELIN 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=855200507
ORANGE 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=380129866
PERNOD_RICARD 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=582041943
PUBLICIS 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=542080601
RENAULT 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=780129987
SAFRAN 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=562082909
SAINT_GOBAIN 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=542039532
SANOFI 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=395030844
SCHNEIDER_ELECTRIC 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=542048574
SOCIETE_GENERALE 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=552120222
STELLANTIS 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=542097924
TELEPERFORMANCE 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=301292702
THALES 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=552059024
TOTALENERGIES 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=542051180
UNIBAIL_RODAMCO 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=682024096
VEOLIA 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=403210032
VINCI 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=552037806
VIVENDI 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=343134763
WORLDLINE 401 Client Error: Unauthorized for url: https://api.pappers.fr/v2/entreprise?api_token=eb133f89f5777dde6b40d461d50a9f255544817502576133&siren=378901946

Empty DataFrame
Columns: []
Index: []